### ISSUE TITLE
How can i send data

### ISSUE THREAD

**Issue by omarherri** [CodyHouse/cd-drag-drop-file-changelog#1]
Hey i was wondering how can i send formData object to backend on form submit using default version(in demo).

**Comment by claudia-romano** [comment]
Hi there, you could use an Ajax call, something like:
```
var xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
  if (this.readyState == 4 && this.status == 200) {
    // success
  }
};
xhttp.open("POST", url, true); // url = form action
xhttp.send(formData);
```
Cheers!

**Comment by omarherri** [comment]
Ohhh thanks a lot for your help.

**Comment by omarherri** [comment]
Hi sorry for bothering you, so basically your suggestion works perfectly, but I explained myself badly. what i really want is be able to submit the form like i do normally with PHP.
So i can look for a solution in the other forums, but before going further, i want to know. if is there a way to attach the files uploaded to the input so i can submit the form with POST data without AJAX.

**Comment by claudia-romano** [comment]
Hi, at the moment it is not possible to submit the form without using some additional AJAX code.

We do have a different component - File Upload - that can be used to upload files:
https://codyhouse.co/ds/components/app/file-upload

With this component, you are able to submit your form as you would normally do. Does this work in you case? Cheers.

**Comment by omarherri** [comment]
Hi, thank your response, well i did some research but obviously i wasn't aware that is impossible to  append a file to input form.
So i already get back to the file upload component.

thanks for your work.
